apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp2"
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/demo-pv
